### ISSUE TITLE
Doc duplicate

### ISSUE THREAD

**Issue by VincentAM** [sethsandaru/eloquent-docs#15]
Hi,
I use your lib with the command : 
`php artisan eloquent:bulk-phpdoc "app/Models/*/*/*.php`
but when we update our model and need to regenerate doc, it's duplicate the doc instead of correct them : 
![image](https://github.com/sethsandaru/eloquent-docs/assets/11472079/b728ab7d-82e7-4a64-8c82-968c9563dbac)
I check all your code and I don't find any code to rewrite comment instead of write a new one.
Have you think about this ?
A solution could be to start your comment with your own keyword and end it with the same
```
/***********ELOGQUEN DOC START *********/
/**
 * Table : 
 .....
**/
/***********ELOGQUEN DOC END *********/
```
and rewrite this section only

are you still updating?
do you think you can include this feature?

**Comment by sethsandaru** [comment]
Hey @VincentAM , thanks for the info and sorries for the late response.

Did you have the phpDoc exists before running the command?

**Comment by VincentAM** [comment]
Hey,

no other comment, but I find your code to replace if exist. The only problem is the indantation
You search */\nclass and in my file, they are a tab (4 spaces) behind the word class so it doestn't replace comment et create another
`if (!Str::contains($fileContent, "*/\nclass $shortClassName")) {`

So I code my command  with this replace before calling your command : 
`preg_replace('#\/\*\*\n.*\* Table[:. \na-zA-Z0-9_\r\t\*=@$\\\/\-|]*class#', 'class', $file_content);`

**Comment by sethsandaru** [comment]
I see. Definitely super rare case and I believe in userland unlikely many people would have your way.

We usually go like this:

```php
/**
* doc here
*/
class User extends Model 
{
// ...
```

I think for this case, best to override the `EloquentDocsGeneratorCommand@writePhpDoc` from your end. So I'll close this one for the time being. 

Thanks for bringing this up, feel free to submit an improvement PR ✌️
