### ISSUE TITLE
Please Upgrade for use under laravel 11.14 and Doctrine 4.0

### ISSUE THREAD

**Issue by solusoftek** [sethsandaru/eloquent-docs#22]
Hi can you please upgrade to fix this problem, running command ` composer require --dev sethphat/eloquent-docs`, on a new fresh installation

` Problem 1
    - sethphat/eloquent-docs[1.0.0, ..., 1.1.2] require laravel/framework ^9|^8 -> found laravel/framework[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but it conflicts with your root composer.json require (^11.9).
    - sethphat/eloquent-docs[1.1.4, ..., 1.2.3] require laravel/framework ^10|^9 -> found laravel/framework[v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.16] but it conflicts with your root composer.json require (^11.9).
    - sethphat/eloquent-docs[2.0.0, ..., 2.0.1] require doctrine/dbal ^3.8 -> found doctrine/dbal[3.8.0, ..., 3.8.6] but it conflicts with your root composer.json require (^4.0).
    - Root composer.json requires sethphat/eloquent-docs * -> satisfiable by sethphat/eloquent-docs[1.0.0, ..., 1.2.3, 2.0.0, 2.0.1].`

Thanks

**Comment by solusoftek** [comment]
composer require sethphat/eloquent-docs:* --dev -W
did the trick *

**Comment by elfif** [comment]
Hello same issue here. 
I tried @solusoftek trick but no luck. 

`sail composer require sethphat/eloquent-docs:* --dev -W`
`./composer.json has been updated`
`Running composer update sethphat/eloquent-docs --with-all-dependencies`
`Loading composer repositories with package information`
`Updating dependencies`
`Your requirements could not be resolved to an installable set of packages.`

  `Problem 1`
`    - Root composer.json requires sethphat/eloquent-docs * -> satisfiable by sethphat/eloquent-docs[1.0.0, ..., 1.2.3, 2.0.0, 2.0.1].`
`    - sethphat/eloquent-docs[1.0.0, ..., 1.1.2] require laravel/framework ^9|^8 -> found laravel/framework[v8.0.0, ..., v8.83.29, v9.0.0, ..., v9.52.18] but it conflicts with your root composer.json require (^11.9).`
`    - sethphat/eloquent-docs[1.1.4, ..., 1.2.3] require laravel/framework ^10|^9 -> found laravel/framework[v9.0.0, ..., v9.52.18, v10.0.0, ..., v10.48.25] but it conflicts with your root composer.json require (^11.9).`
`    - sethphat/eloquent-docs[2.0.0, ..., 2.0.1] require doctrine/dbal ^3.8 -> found doctrine/dbal[3.8.0, ..., 3.9.3] but it conflicts with your root composer.json require (^4.2).`
