### ISSUE TITLE
Unable to read ENUMs

### ISSUE THREAD

**Issue by Prophet731** [sethsandaru/eloquent-docs#4]
```
Unknown database type enum requested, Doctrine\DBAL\Platforms\MariaDb1027Platform may not support it.
```

I have a table that uses an ENUM as the column type. This is more a Doctrine issue then this specific packages but maybe adding a some sort of try catch when the package encounters this and just notify the user it can't do that so needs to be manually added.

**Comment by sethsandaru** [comment]
thanks @Prophet731 , I found the issue. This should be fixed in v1.1.1

Basically, `enum` will be considered as `string` (it is a list of literal under DB-layer)
